### ISSUE TITLE
All entries show bucket `.work`

### ISSUE THREAD

**Issue by JanPokorny** [mertd/shovel#22]
Looks like showing the bucket name is broken:

![obrazek](https://user-images.githubusercontent.com/4580066/103065548-2068c180-45b7-11eb-9249-a354c0434bf9.png)

**Comment by mertd** [comment]
Thank you!

Seems like this bug got introduced in https://github.com/mertd/shovel-data/pull/11. 
It's fixed in https://github.com/mertd/shovel-data/pull/12 and should be working again.

**Comment by JanPokorny** [comment]
Indeed, thanks for the quick fix!
