### ISSUE TITLE
Support URL query

### ISSUE THREAD

**Issue by examosa** [mertd/shovel#32]
Hello! I'm not sure if this is intended behavior, but the application doesn't seem to work if the search query has already been set in the URL.

### Expected
navigating to https://shovel.sh/search?q=git should display search results for `git`

### Actual
Search results appear for a moment and disappear

**Comment by mertd** [comment]
Thank you for the report! You are right, accessing the link directly does not work very reliably. This will need a revisit of how setting and reading the URL interacts with triggering the search.
