### ISSUE TITLE
Page freezes as first few characters entered

### ISSUE THREAD

**Issue by tech189** [mertd/shovel#34]
It would be nice if the search waited a second for you to type in your query otherwise it starts to lag as it searches for the first few characters which have thousands of results, especially noticeable on a mobile browser!

**Comment by mertd** [comment]
Thanks for the feedback! Currently the waiting time between input and search is set to 300ms. It may be a good idea to allow for a bit more time, especially for short inputs.

**Comment by mertd** [comment]
A workaround has been implemented in the PR linked above, and the issue should be addressed fully in #42. I will therefore close this PR. Thanks again for the feedback!
